name = "nexa-suite-hub"
main = "dist/server/server.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"

[[routes]]
pattern = "nexasoluciones.cloud"
zone_name = "nexasoluciones.cloud"
custom_domain = true