name: Supabase Migrations

on:
  workflow_dispatch:

jobs:
  push-migrations:
    runs-on: ubuntu-latest
    name: Push Supabase migrations

    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Push migrations
        run: |
          supabase db push --yes
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}